### ISSUE TITLE
QEMU Stuck on "Booting Linux virt" When Starting Alpine Linux

### ISSUE THREAD

**Issue by 14790897** [cyberkernelofficial/docker-in-termux#16]
I am attempting to run Alpine Linux (version 3.19.1) using QEMU on my system, but the boot process is continuously stuck at "Booting Linux virt".
I run  `qemu-system-x86_64 -machine q35 -m 1024 -smp cpus=2 -cpu qemu64 -drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-x86_64-code.fd -netdev user,id=n1,dns=8.8.8.8,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 -cdrom alpine-virt-3.19.1-x86_64.iso -nographic alpine.img` 

![image](https://github.com/user-attachments/assets/e8ac9209-b835-42b9-b5f3-6a4d0a1735f0)

**Comment by 14790897** [comment]
![image](https://github.com/user-attachments/assets/e31a1916-f369-4e4b-a217-84f5379dc87d)

**Comment by william-stacken** [comment]
Try waiting for a bit, thought I had the same problem but after 5-10 minutes I got the login prompt.

**Comment by 14790897** [comment]
thank you
